version: "3.9"
services:
  web:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=wiredb"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=1234"

volumes:
  postgres_data:
