version: "3.8"
services:
  app:
    build: . # build from Dockerfile in current directory
    volumes:
      - ./wire_project/:/app #
    restart: always
    ports:
      - "8000:8000" # map port 8000 on host to port 8000 in container
    image: app:latest # tag the image as app:latest
    container_name: app_container # name of the container 
    command: >
      sh -c "
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db # start the db container before starting the app container
  db:
    image: postgres:15 # use the latest postgres image
    #    volumes:
    #      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432" # map port 8000 on host to port 8000 in container
    container_name: db_container

# services:
#   db:
#     image: postgres
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=my_db
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=1234
#   web:
#     build: .
#     # command: python manage.py runserver
#     # volumes:
#     #   - .:/code
#     ports:
#       - "8000:8000"
#     environment:
#       - POSTGRES_NAME=my_db
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=1234
#     depends_on:
#       - db

# version: "3.9"
# services:
#   web:
#     build: .
#     ports:
#       - "8001:8000"
#     depends_on:
#       - db
#   db:
#     image: postgres:15
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - "POSTGRES_HOST_AUTH_METHOD=trust"
#       - "POSTGRES_DB=wiredb"
#       - "POSTGRES_USER=postgres"
#       - "POSTGRES_PASSWORD=1234"

# volumes:
#   postgres_data:
