# Generated by Django 4.1.3 on 2022-12-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire_app', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
