# Generated by Django 4.1.3 on 2022-12-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire_app', '0004_post_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
