# Generated by Django 4.1.3 on 2022-12-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire_app', '0005_remove_post_image_alter_post_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
